[package]
name = "rust_chip8"
version = "0.1.0"
authors = ["truelossless <esteban.gressard@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
sdl2 = "0.32.2"
log = "0.4.7"
simple_logger = "1.3.0"
clap = "2.33.0"